#ifndef GLOBALS_H
#define GLOBALS_H

#endif // GLOBALS_H

enum StatusCode{
        LOGIN_SUCCESS,
        LOGIN_FAILURE_NONMATCHING_CREDENTIALS
};

#define GLOBALS_USERNAME_MIN_CHARACTER 5
#define GLOBALS_USERNAME_MAX_CHARACTER 10

#define GLOBALS_PASSWORD_MIN_CHARACTER 5
#define GLOBALS_PASSWORD_MAX_CHARACTER 10

#define GLOBALS_RESORT_NUMBER_CHARACTER 4

